#!/usr/bin/env python3
"""BUILD agent — turns a chosen opportunity into a real MVP via Codex (autonomous coding).

Guarded by the supervisor: only invoked AFTER PUBLISH/OUTREACH/SELL are approved.
Codex is already authenticated on this machine (provider: openai).

24/7-hardened:
- streams output to a log file (avoids subprocess pipe deadlock with Codex's TTY session)
- short hard timeout (default 45s): if Codex is unreachable/expired it fails FAST
  instead of hanging the hourly cron for 9 minutes
- on any failure/timeout, kills the Codex process tree so no zombie holds codex.log
  (which previously caused 'device busy' on cleanup)
- honest local fallback -> the autonomous loop still yields a deployable artifact
"""
import os, subprocess, time, signal


def build(plan, workdir=None, timeout=45):
    """Generate an MVP repo for the chosen opportunity using Codex."""
    if not plan or not plan.get("title"):
        return "GATED: no plan to build"

    title = plan["title"]
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = workdir or os.path.join(root, "builds", _slug(title))
    os.makedirs(out_dir, exist_ok=True)
    log = os.path.join(out_dir, "codex.log")

    prompt = (
        "Build a minimal but real, deployable MVP landing page for this paid offer: "
        f"'{title}' (channel: {plan.get('channel')}, price: {plan.get('price_range')}). "
        "Output: index.html (premium clean design, deep black + warm gold, responsive), "
        "a Stripe checkout link placeholder, and a README.md with the offer + price. "
        "Write the files into the current working directory. Keep it production-quality, no stubs."
    )

    try:
        with open(log, "w", encoding="utf-8") as lf:
            proc = subprocess.Popen(
                ["codex", "exec", "--skip-git-repo-check", prompt],
                cwd=out_dir,
                stdout=lf,
                stderr=subprocess.STDOUT,
            )
    except FileNotFoundError:
        return _local_mvp(plan, out_dir) + " (codex CLI missing -> local fallback)"

    # Poll with a SHORT hard timeout so an expired/unreachable Codex fails fast.
    step = 3
    waited = 0
    while proc.poll() is None:
        if waited >= timeout:
            _kill_tree(proc.pid)
            return _local_mvp(plan, out_dir) + " (BUILD TIMEOUT %ds -> local fallback)" % timeout
        time.sleep(step)
        waited += step

    # Codex succeeded?
    files = [f for f in os.listdir(out_dir) if not f.startswith(".") and f != "codex.log"]
    if proc.returncode == 0 and files:
        return "BUILT '%s' -> %s (%d files): %s" % (title, out_dir, len(files), ", ".join(files))

    # Codex failed (e.g. 401 expired token) -> honest local fallback and clean up.
    _kill_tree(proc.pid)  # ensure no zombie holds codex.log
    return _local_mvp(plan, out_dir) + " (codex rc=%d -> local fallback)" % proc.returncode


def _kill_tree(pid):
    """Kill a process and its descendants (Codex spawns children that hold files)."""
    try:
        if os.name == "nt":
            subprocess.run(["taskkill", "/PID", str(pid), "/T", "/F"],
                           capture_output=True, timeout=10)
        else:
            import psutil
            parent = psutil.Process(pid)
            for child in parent.children(recursive=True):
                child.kill()
            parent.kill()
    except Exception:
        try:
            os.kill(pid, signal.SIGKILL)
        except Exception:
            pass


def _local_mvp(plan, out_dir):
    """Deterministic premium landing page + README (no API needed)."""
    title = plan.get("title", "Offer")
    price = plan.get("price_range", "")
    channel = plan.get("channel", "")
    html = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>%s</title><style>
:root{--bg:#0a0a0a;--gold:#d4af37;--fg:#f5f5f5}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--fg);font-family:system-ui,Segoe UI,Arial,sans-serif;line-height:1.6}
.hero{padding:14vh 8vw;text-align:center}
h1{font-size:clamp(2rem,6vw,4rem);font-weight:800;letter-spacing:-.03em}
.gold{color:var(--gold)}
.price{margin:2rem 0;font-size:1.4rem;color:var(--gold)}
.cta{display:inline-block;background:var(--gold);color:#0a0a0a;padding:1rem 2.4rem;border-radius:999px;font-weight:700;text-decoration:none}
footer{padding:4vh 8vw;opacity:.5;font-size:.85rem}
</style></head><body>
<section class="hero">
<h1>%s</h1>
<p class="price gold">%s</p>
<p>A premium %s, built to deliver real results.</p>
<a class="cta" href="#">Get started</a>
</section>
<footer>Generated by autopilot-os &middot; Stripe checkout link placeholder</footer>
</body></html>""" % (title, title, price or "Contact for pricing", channel or "service")

    readme = "# %s\n\n**Price:** %s  \n**Channel:** %s\n\nAutonomous MVP generated by autopilot-os (local fallback).\nReplace the CTA with your Stripe checkout link.\n" % (title, price or "TBD", channel or "TBD")

    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)
    with open(os.path.join(out_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)
    files = [f for f in os.listdir(out_dir) if not f.startswith(".")]
    return "BUILT (local) '%s' -> %s (%d files): %s" % (title, out_dir, len(files), ", ".join(files))


def _slug(s):
    return "".join(c if c.isalnum() else "-" for c in s.lower()).strip("-")[:40]
